# Generated by Django 4.2 on 2023-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeustutub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fechaFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
